// Auto-generated by SCUG
// DO NOT EDIT MANUALLY!

using System;
using UnityEngine;
using UnityEngine.SceneManagement;
using System.Text.Json;
using System.Text.Json.Serialization;

[JsonConverter(typeof(MapsConverter))]
public readonly struct Maps : System.IEquatable<Maps>
{
    private readonly string _value;
    private Maps(string value) => _value = value;
    public override string ToString() => _value ?? string.Empty;
    public string GetString() => _value ?? string.Empty;
    public static implicit operator string(Maps map) => map._value;
    public static implicit operator Maps(string value) => new Maps(value);
    public bool Equals(Maps other) => _value == other._value;
    public override bool Equals(object obj) => obj is Maps other && Equals(other);
    public override int GetHashCode() => _value?.GetHashCode() ?? 0;
    public static bool operator ==(Maps left, Maps right) => left.Equals(right);
    public static bool operator !=(Maps left, Maps right) => !left.Equals(right);

    public class MapsConverter : JsonConverter<Maps>
    {
        public override Maps Read(ref Utf8JsonReader reader, System.Type typeToConvert, JsonSerializerOptions options)
        {
            if (reader.TokenType == JsonTokenType.String) return reader.GetString();
            if (reader.TokenType == JsonTokenType.Number && reader.TryGetInt32(out int value))
            {
                if (value >= 0 && value < All.Length) return All[value];
            }
            return default;
        }
        public override void Write(Utf8JsonWriter writer, Maps value, JsonSerializerOptions options) => writer.WriteStringValue(value.ToString());
    }

    public static readonly Maps MainMenu = new Maps("MainMenu");
    public static readonly Maps Level1 = new Maps("Level1");

    public static readonly Maps[] All = new Maps[]
    {
        MainMenu,
        Level1,
    };
}

public static class Map
{
    public static string GetSceneName(Maps map) => map.ToString();

    public static void Load(Maps map)
    {
        string sceneName = GetSceneName(map);
        if (string.IsNullOrEmpty(sceneName)) return;
        if (Application.isEditor && SceneUtility.GetBuildIndexByScenePath(sceneName) == -1)
        {
            Debug.LogError($"Scene '{sceneName}' not found in Build Settings! Make sure it's added and names match.");
            return;
        }
        SceneManager.LoadScene(sceneName);
    }

    public static bool Is(Maps map)
    {
        return SceneManager.GetActiveScene().name.Equals(GetSceneName(map), StringComparison.OrdinalIgnoreCase);
    }

    public static Maps GetCurrentMap()
    {
        string currentName = SceneManager.GetActiveScene().name;
        foreach (Maps map in Maps.All)
        {
            if (map.ToString().Equals(currentName, StringComparison.OrdinalIgnoreCase))
            {
                return map;
            }
        }
        Debug.LogWarning($"Current scene '{currentName}' is not defined in the Maps Enum.");
        return default;
    }

    public static void Reload()
    {
        SceneManager.LoadScene(SceneManager.GetActiveScene().buildIndex);
    }

    public static int GetBuildIndex(Maps map)
    {
        return SceneUtility.GetBuildIndexByScenePath(GetSceneName(map));
    }
}
