// Auto-generated by SCUG
// DO NOT EDIT MANUALLY!

using UnityEngine;

public static class Res
{
    public static class Prefabs
    {
        public const string Path = "Prefabs";
        public static T Get<T>(string name) where T : UnityEngine.Object => Resources.Load<T>(Path + "/" + name);
        public static GameObject GetObj(string name) => Resources.Load<GameObject>(Path + "/" + name);
        public static class UIPrefabs
        {
            public const string Path = "Prefabs/UIPrefabs";
            public static T Get<T>(string name) where T : UnityEngine.Object => Resources.Load<T>(Path + "/" + name);
            public static GameObject GetObj(string name) => Resources.Load<GameObject>(Path + "/" + name);
            public static class OverlayCanvas
            {
                public const string Path = "Prefabs/UIPrefabs/OverlayCanvas";
                public static T Get<T>(string name) where T : UnityEngine.Object => Resources.Load<T>(Path + "/" + name);
                public static GameObject GetObj(string name) => Resources.Load<GameObject>(Path + "/" + name);
                public static GameObject CanvasOverlay => Resources.Load<GameObject>("Prefabs/UIPrefabs/OverlayCanvas/CanvasOverlay");
            }
        }
        public static class EnvironmentPrefabs
        {
            public const string Path = "Prefabs/EnvironmentPrefabs";
            public static T Get<T>(string name) where T : UnityEngine.Object => Resources.Load<T>(Path + "/" + name);
            public static GameObject GetObj(string name) => Resources.Load<GameObject>(Path + "/" + name);
            public static GameObject Tree => Resources.Load<GameObject>("Prefabs/EnvironmentPrefabs/Tree");
        }
    }
}
