// Auto-generated by SCUG
// DO NOT EDIT MANUALLY!

using System.Collections.Generic;
using UnityEngine;
using System.Text.Json;
using System.Text.Json.Serialization;

[JsonConverter(typeof(TagsConverter))]
public readonly struct Tags : System.IEquatable<Tags>
{
    private readonly string _value;
    private Tags(string value) => _value = value;
    public override string ToString() => _value;
    public string GetString() => _value;
    public static implicit operator string(Tags tag) => tag._value;
    public static implicit operator Tags(string value) => new Tags(value);
    public bool Equals(Tags other) => _value == other._value;
    public override bool Equals(object obj) => obj is Tags other && Equals(other);
    public override int GetHashCode() => _value?.GetHashCode() ?? 0;
    public static bool operator ==(Tags left, Tags right) => left.Equals(right);
    public static bool operator !=(Tags left, Tags right) => !left.Equals(right);

    public class TagsConverter : JsonConverter<Tags>
    {
        public override Tags Read(ref Utf8JsonReader reader, System.Type typeToConvert, JsonSerializerOptions options)
        {
            if (reader.TokenType == JsonTokenType.String) return reader.GetString();
            return default;
        }
        public override void Write(Utf8JsonWriter writer, Tags value, JsonSerializerOptions options) => writer.WriteStringValue(value.ToString());
    }

    public static readonly Tags Player = new Tags("Player");
    public static readonly Tags Enemy = new Tags("Enemy");
    public static readonly Tags Custom_tag = new Tags("custom_tag");
}

public class Tag : MonoBehaviour
{
    public static GameObject[] FindGameObjectsWith(Tags tag)
    {
        return GameObject.FindGameObjectsWithTag(tag.GetString());
    }

    public static GameObject FindGameObjectWith(Tags tag)
    {
        return GameObject.FindGameObjectWithTag(tag.GetString());
    }

    public static GameObject FindWith(Tags tag)
    {
        return GameObject.FindWithTag(tag.GetString());
    }

    public static GameObject[] FindGameObjectsIn(GameObject parent, Tags tag)
    {
        List<GameObject> result = new List<GameObject>();
        string tagStr = tag.GetString();
        foreach (Transform t in parent.GetComponentsInChildren<Transform>(true))
        {
            if (t.CompareTag(tagStr)) result.Add(t.gameObject);
        }
        return result.ToArray();
    }

    public static GameObject FindGameObjectIn(GameObject parent, Tags tag)
    {
        string tagStr = tag.GetString();
        foreach (Transform t in parent.GetComponentsInChildren<Transform>(true))
        {
            if (t.CompareTag(tagStr)) return t.gameObject;
        }
        return null;
    }
}
