package generator

import (
	"fmt"
	"io/fs"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"

	"v1m-SCUG/internal/utils"
)

type ResNode struct {
	Name      string
	Sanitized string
	Path      string
	Type      string
	IsDir     bool
	Children  map[string]*ResNode
}

func GenerateResources(resourcesDir, outputDir string) {
	rootNode := &ResNode{
		Name:      "Res",
		Sanitized: "Res",
		IsDir:     true,
		Children:  make(map[string]*ResNode),
	}

	filepath.WalkDir(resourcesDir, func(pathStr string, d fs.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if d.IsDir() {
			return nil
		}

		relPath, err := filepath.Rel(resourcesDir, pathStr)
		if err != nil {
			return nil
		}

		slashPath := filepath.ToSlash(relPath)
		if strings.HasSuffix(slashPath, ".meta") {
			return nil
		}

		ext := filepath.Ext(slashPath)
		resPath := strings.TrimSuffix(slashPath, ext)
		parts := strings.Split(resPath, "/")

		cur := rootNode
		for i, part := range parts {
			isLast := i == len(parts)-1
			if _, exists := cur.Children[part]; !exists {
				cur.Children[part] = &ResNode{
					Name:      part,
					Sanitized: utils.SanitizeIdentifier(part),
					IsDir:     !isLast,
					Children:  make(map[string]*ResNode),
				}
			}
			cur = cur.Children[part]
			if isLast {
				cur.Path = resPath
				cur.Type = getTypeFromExt(ext)
			}
		}

		return nil
	})

	var sb strings.Builder
	sb.WriteString("// Auto-generated by SCUG\n")
	sb.WriteString("// DO NOT EDIT MANUALLY!\n\n")
	sb.WriteString("using UnityEngine;\n\n")

	// Global namespace
	writeResNode(&sb, rootNode, "", "", "")

	outPath := filepath.Join(outputDir, "Global")
	os.MkdirAll(outPath, 0755)
	ioutil.WriteFile(filepath.Join(outPath, "Res.cs"), []byte(sb.String()), 0644)
	fmt.Println("Generated: Res.cs")
}

func writeResNode(sb *strings.Builder, node *ResNode, indent string, currentPath string, parentName string) {
	if node.IsDir {
		if node.Sanitized == "Res" {
			sb.WriteString(fmt.Sprintf("%spublic static class %s\n%s{\n", indent, node.Sanitized, indent))
		} else {
			sb.WriteString(fmt.Sprintf("%spublic static class %s\n%s{\n", indent, node.Sanitized, indent))
			sb.WriteString(fmt.Sprintf("%s    public const string Path = \"%s\";\n", indent, currentPath))
			sb.WriteString(fmt.Sprintf("%s    public static T Get<T>(string name) where T : UnityEngine.Object => Resources.Load<T>(Path + \"/\" + name);\n", indent))
			sb.WriteString(fmt.Sprintf("%s    public static GameObject GetObj(string name) => Resources.Load<GameObject>(Path + \"/\" + name);\n", indent))
		}

		for _, child := range node.Children {
			childPath := currentPath
			if childPath == "" {
				childPath = child.Name
			} else {
				childPath = currentPath + "/" + child.Name
			}
			writeResNode(sb, child, indent+"    ", childPath, node.Sanitized)
		}
		sb.WriteString(fmt.Sprintf("%s}\n", indent))
	} else {
		propName := node.Sanitized
		if propName == parentName {
			propName += "_"
		}
		sb.WriteString(fmt.Sprintf("%spublic static %s %s => Resources.Load<%s>(\"%s\");\n", indent, node.Type, propName, node.Type, node.Path))
	}
}

func getTypeFromExt(ext string) string {
	switch strings.ToLower(ext) {
	case ".png", ".jpg", ".jpeg", ".tga", ".bmp", ".tif", ".tiff":
		return "Sprite"
	case ".mat":
		return "Material"
	case ".prefab":
		return "GameObject"
	case ".mp3", ".wav", ".ogg", ".aiff":
		return "AudioClip"
	case ".anim":
		return "AnimationClip"
	case ".controller":
		return "RuntimeAnimatorController"
	case ".asset":
		return "ScriptableObject"
	case ".txt", ".json", ".csv", ".xml", ".html", ".md", ".bytes":
		return "TextAsset"
	case ".fontsettings", ".ttf", ".otf":
		return "Font"
	default:
		return "Object"
	}
}