package generator

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"v1m-SCUG/internal/utils"
)

func GenerateScenes(projectRoot, outputDir string) {
	settingsPath := filepath.Join(projectRoot, "ProjectSettings", "EditorBuildSettings.asset")
	content, err := ioutil.ReadFile(settingsPath)
	if err != nil {
		return
	}

	re := regexp.MustCompile(`-\s*enabled:\s*1\s*\n\s*path:\s*(.*?)\n`)
	matches := re.FindAllStringSubmatch(string(content), -1)

	var scenes []string
	for _, m := range matches {
		path := m[1]
		name := strings.TrimSuffix(filepath.Base(path), ".unity")
		scenes = append(scenes, name)
	}

	if len(scenes) == 0 {
		return
	}

	var sb strings.Builder
	sb.WriteString("// Auto-generated by SCUG\n")
	sb.WriteString("// DO NOT EDIT MANUALLY!\n\n")
	sb.WriteString("using System;\n")
	sb.WriteString("using UnityEngine;\n")
	sb.WriteString("using UnityEngine.SceneManagement;\n")
	sb.WriteString("using System.Text.Json;\n")
	sb.WriteString("using System.Text.Json.Serialization;\n\n")

	sb.WriteString("[JsonConverter(typeof(MapsConverter))]\n")
	sb.WriteString("public readonly struct Maps : System.IEquatable<Maps>\n{\n")
	sb.WriteString("    private readonly string _value;\n")
	sb.WriteString("    private Maps(string value) => _value = value;\n")
	sb.WriteString("    public override string ToString() => _value ?? string.Empty;\n")
	sb.WriteString("    public string GetString() => _value ?? string.Empty;\n")
	sb.WriteString("    public static implicit operator string(Maps map) => map._value;\n")
	sb.WriteString("    public static implicit operator Maps(string value) => new Maps(value);\n")
	sb.WriteString("    public bool Equals(Maps other) => _value == other._value;\n")
	sb.WriteString("    public override bool Equals(object obj) => obj is Maps other && Equals(other);\n")
	sb.WriteString("    public override int GetHashCode() => _value?.GetHashCode() ?? 0;\n")
	sb.WriteString("    public static bool operator ==(Maps left, Maps right) => left.Equals(right);\n")
	sb.WriteString("    public static bool operator !=(Maps left, Maps right) => !left.Equals(right);\n\n")

	sb.WriteString("    public class MapsConverter : JsonConverter<Maps>\n    {\n")
	sb.WriteString("        public override Maps Read(ref Utf8JsonReader reader, System.Type typeToConvert, JsonSerializerOptions options)\n        {\n")
	sb.WriteString("            if (reader.TokenType == JsonTokenType.String) return reader.GetString();\n")
	sb.WriteString("            if (reader.TokenType == JsonTokenType.Number && reader.TryGetInt32(out int value))\n            {\n")
	sb.WriteString("                if (value >= 0 && value < All.Length) return All[value];\n")
	sb.WriteString("            }\n")
	sb.WriteString("            return default;\n        }\n")
	sb.WriteString("        public override void Write(Utf8JsonWriter writer, Maps value, JsonSerializerOptions options) => writer.WriteStringValue(value.ToString());\n")
	sb.WriteString("    }\n\n")

	for _, scene := range scenes {
		sb.WriteString(fmt.Sprintf("    public static readonly Maps %s = new Maps(\"%s\");\n", utils.SanitizeIdentifier(scene), scene))
	}

	sb.WriteString("\n    public static readonly Maps[] All = new Maps[]\n    {\n")
	for _, scene := range scenes {
		sb.WriteString(fmt.Sprintf("        %s,\n", utils.SanitizeIdentifier(scene)))
	}
	sb.WriteString("    };\n")
	sb.WriteString("}\n\n")

	sb.WriteString("public static class Map\n{\n")
	sb.WriteString("    public static string GetSceneName(Maps map) => map.ToString();\n\n")

	sb.WriteString("    public static void Load(Maps map)\n    {\n")
	sb.WriteString("        string sceneName = GetSceneName(map);\n")
	sb.WriteString("        if (string.IsNullOrEmpty(sceneName)) return;\n")
	sb.WriteString("        if (Application.isEditor && SceneUtility.GetBuildIndexByScenePath(sceneName) == -1)\n        {\n")
	sb.WriteString("            Debug.LogError($\"Scene '{sceneName}' not found in Build Settings! Make sure it's added and names match.\");\n")
	sb.WriteString("            return;\n        }\n")
	sb.WriteString("        SceneManager.LoadScene(sceneName);\n    }\n\n")

	sb.WriteString("    public static bool Is(Maps map)\n    {\n")
	sb.WriteString("        return SceneManager.GetActiveScene().name.Equals(GetSceneName(map), StringComparison.OrdinalIgnoreCase);\n    }\n\n")

	sb.WriteString("    public static Maps GetCurrentMap()\n    {\n")
	sb.WriteString("        string currentName = SceneManager.GetActiveScene().name;\n")
	sb.WriteString("        foreach (Maps map in Maps.All)\n        {\n")
	sb.WriteString("            if (map.ToString().Equals(currentName, StringComparison.OrdinalIgnoreCase))\n            {\n")
	sb.WriteString("                return map;\n            }\n        }\n")
	sb.WriteString("        Debug.LogWarning($\"Current scene '{currentName}' is not defined in the Maps Enum.\");\n")
	sb.WriteString("        return default;\n    }\n\n")

	sb.WriteString("    public static void Reload()\n    {\n")
	sb.WriteString("        SceneManager.LoadScene(SceneManager.GetActiveScene().buildIndex);\n    }\n\n")

	sb.WriteString("    public static int GetBuildIndex(Maps map)\n    {\n")
	sb.WriteString("        return SceneUtility.GetBuildIndexByScenePath(GetSceneName(map));\n    }\n")
	sb.WriteString("}\n")

	outPath := filepath.Join(outputDir, "Global")
	os.MkdirAll(outPath, 0755)
	ioutil.WriteFile(filepath.Join(outPath, "Map.cs"), []byte(sb.String()), 0644)
	fmt.Println("Generated: Map.cs")
}