package generator

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"v1m-SCUG/internal/utils"
)

func GenerateTags(projectRoot, outputDir string) {
	settingsPath := filepath.Join(projectRoot, "ProjectSettings", "TagManager.asset")
	content, err := ioutil.ReadFile(settingsPath)
	if err != nil {
		return
	}

	tagsBlock := ""
	tagsRe := regexp.MustCompile(`(?s)  tags:\s*\n(.*?)  layers:`)
	tagsMatch := tagsRe.FindStringSubmatch(string(content))
	if len(tagsMatch) > 1 {
		tagsBlock = tagsMatch[1]
	}

	var tags []string
	lines := strings.Split(tagsBlock, "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "- ") {
			tag := strings.TrimSpace(strings.TrimPrefix(line, "- "))
			if tag != "" {
				tags = append(tags, tag)
			}
		}
	}

	if len(tags) == 0 {
		return
	}

	var sb strings.Builder
	sb.WriteString("// Auto-generated by SCUG\n")
	sb.WriteString("// DO NOT EDIT MANUALLY!\n\n")
	sb.WriteString("using System.Collections.Generic;\n")
	sb.WriteString("using UnityEngine;\n")
	sb.WriteString("using System.Text.Json;\n")
	sb.WriteString("using System.Text.Json.Serialization;\n\n")

	sb.WriteString("[JsonConverter(typeof(TagsConverter))]\n")
	sb.WriteString("public readonly struct Tags : System.IEquatable<Tags>\n{\n")
	sb.WriteString("    private readonly string _value;\n")
	sb.WriteString("    private Tags(string value) => _value = value;\n")
	sb.WriteString("    public override string ToString() => _value;\n")
	sb.WriteString("    public string GetString() => _value;\n")
	sb.WriteString("    public static implicit operator string(Tags tag) => tag._value;\n")
	sb.WriteString("    public static implicit operator Tags(string value) => new Tags(value);\n")
	sb.WriteString("    public bool Equals(Tags other) => _value == other._value;\n")
	sb.WriteString("    public override bool Equals(object obj) => obj is Tags other && Equals(other);\n")
	sb.WriteString("    public override int GetHashCode() => _value?.GetHashCode() ?? 0;\n")
	sb.WriteString("    public static bool operator ==(Tags left, Tags right) => left.Equals(right);\n")
	sb.WriteString("    public static bool operator !=(Tags left, Tags right) => !left.Equals(right);\n\n")

	sb.WriteString("    public class TagsConverter : JsonConverter<Tags>\n    {\n")
	sb.WriteString("        public override Tags Read(ref Utf8JsonReader reader, System.Type typeToConvert, JsonSerializerOptions options)\n        {\n")
	sb.WriteString("            if (reader.TokenType == JsonTokenType.String) return reader.GetString();\n")
	sb.WriteString("            return default;\n        }\n")
	sb.WriteString("        public override void Write(Utf8JsonWriter writer, Tags value, JsonSerializerOptions options) => writer.WriteStringValue(value.ToString());\n")
	sb.WriteString("    }\n\n")

	for _, tag := range tags {
		sanitized := utils.SanitizeIdentifier(tag)
		sb.WriteString(fmt.Sprintf("    public static readonly Tags %s = new Tags(\"%s\");\n", sanitized, tag))
	}
	sb.WriteString("}\n\n")

	sb.WriteString("public class Tag : MonoBehaviour\n{\n")
	sb.WriteString("    public static GameObject[] FindGameObjectsWith(Tags tag)\n    {\n")
	sb.WriteString("        return GameObject.FindGameObjectsWithTag(tag.GetString());\n    }\n\n")

	sb.WriteString("    public static GameObject FindGameObjectWith(Tags tag)\n    {\n")
	sb.WriteString("        return GameObject.FindGameObjectWithTag(tag.GetString());\n    }\n\n")

	sb.WriteString("    public static GameObject FindWith(Tags tag)\n    {\n")
	sb.WriteString("        return GameObject.FindWithTag(tag.GetString());\n    }\n\n")

	sb.WriteString("    public static GameObject[] FindGameObjectsIn(GameObject parent, Tags tag)\n    {\n")
	sb.WriteString("        List<GameObject> result = new List<GameObject>();\n")
	sb.WriteString("        string tagStr = tag.GetString();\n")
	sb.WriteString("        foreach (Transform t in parent.GetComponentsInChildren<Transform>(true))\n        {\n")
	sb.WriteString("            if (t.CompareTag(tagStr)) result.Add(t.gameObject);\n        }\n")
	sb.WriteString("        return result.ToArray();\n    }\n\n")

	sb.WriteString("    public static GameObject FindGameObjectIn(GameObject parent, Tags tag)\n    {\n")
	sb.WriteString("        string tagStr = tag.GetString();\n")
	sb.WriteString("        foreach (Transform t in parent.GetComponentsInChildren<Transform>(true))\n        {\n")
	sb.WriteString("            if (t.CompareTag(tagStr)) return t.gameObject;\n        }\n")
	sb.WriteString("        return null;\n    }\n")
	sb.WriteString("}\n")

	outPath := filepath.Join(outputDir, "Global")
	os.MkdirAll(outPath, 0755)
	ioutil.WriteFile(filepath.Join(outPath, "Tags.cs"), []byte(sb.String()), 0644)
	fmt.Println("Generated: Tags.cs")
}